blueprint:
  domain: automation
  name: z2m - Philips Hue Dimmer Switch - Multi-Press and Hold
  author: MPFGlaser
  homeassistant:
    min_version: 2024.6.0
  description: >
    ## [z2m] Philips Hue Dimmer Switch - Multi-Press and Hold Automation (v0.0.1) by MPFGlaser
    
    Automation for Philips Hue Dimmer Switch (929002398602) to handle multi-press and hold actions.  
    Might support 324131092621 as well, but this is not tested.  

    Aims to provide the same functionality as the Philips Hue Dimmer Switch provides when used with the Philips Hue Bridge.  


    *Only for use with Zigbee2MQTT*

    ### Features

    - Supports single presses, holds, and multi-presses (2-5 clicks) for all buttons.  
    
    - Multi-press support is optional, not assigning a helper will disable multi-presses for that button. 
    
    - Uses Input Counters as helpers to track multi-press counts.  
     
    - Native Hue-like behaviour: Waits for a short delay after the last press to determine if more presses are coming before executing the action.
  input:
    dimmer_switch:
      name: Philips Hue Dimmer Switch
      description: Choose the Philips Hue Dimmer Switch device to configure
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Philips
              model: Hue dimmer switch
          multiple: false
    helper_on_button_presses:
      name: (Required) Helper - "On" Button Presses
      description:
        Input Counter used to store the amount of clicks fired by the controller.
        Manually create a counter helper entity for this, with minimum 0, maximum 5, initial value 0, and step size 1.
      default: ""
      selector:
        entity:
          domain:
            - counter
          multiple: false
          reorder: false
    helper_up_button_presses:
      name: (Required) Helper - "Up" Button Presses
      description:
        Input Counter used to store the amount of clicks fired by the controller.
        Manually create a counter helper entity for this, with minimum 0, maximum 5, initial value 0, and step size 1.
      default: ""
      selector:
        entity:
          domain:
            - counter
          multiple: false
          reorder: false       
    helper_down_button_presses:
      name: (Required) Helper - "Down" Button Presses
      description:
        Input Counter used to store the amount of clicks fired by the controller.
        Manually create a counter helper entity for this, with minimum 0, maximum 5, initial value 0, and step size 1.
      default: ""
      selector:
        entity:
          domain:
            - counter
          multiple: false
          reorder: false   
    helper_off_button_presses:
      name: (Required) Helper - "Off"/"Hue" Button Presses
      description:
        Input Counter used to store the amount of clicks fired by the controller.
        Manually create a counter helper entity for this, with minimum 0, maximum 5, initial value 0, and step size 1.
      default: ""
      selector:
        entity:
          domain:
            - counter
          multiple: false
          reorder: false   
mode: single
max_exceeded: silent
variables:
  device_id: !input dimmer_switch
triggers:
  - domain: mqtt
    device_id: "{{ device_id }}"
    type: action
    subtype: off_press_release
    trigger: device
    id: off_click
